import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import NavBar from "../components/NavBar";
import BudgetHeader from "../components/BugetHeader";
import Login from "../components/Login";
import SpendingActivity from "../components/SpendingActivity";
import type { Budget } from "@prisma/client";

const Home: NextPage = () => {

  const {data: session} = useSession()
  const {data: userBudget, isLoading} = trpc.db.getBudget.useQuery()

  console.log(session);
  

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex flex-col pb-5 bg-green-100 bg-img">
        <NavBar />
        {!session ? (<Login />) : <BudgetHeader userBudget={userBudget as Budget} />}
        {/* <div className="h-full py-5">
          <div className="h-48 ml-10 bg-slate-300 w-[45%] rounded">

          </div>

        </div> */}
        {/* <BudgetHeader /> */}
        <SpendingActivity userBudget={userBudget as Budget} />
        
      </main>
    </>
  );
};

export default Home;


